services:
  postgres:
    image: postgres:15.0
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - postgres
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/usr/src/app # Mounts the current directory to the container
      - /usr/src/app/node_modules # Ensures the node_modules from the container are used
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
